version: '3'
services:
  postgres13:
    image: postgres:13
    restart: unless-stopped
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: 'prisma'
      PGDATA: '/pgtmpfs13'
    ports:
      - '5432:5432'
    networks:
      - databases
    tmpfs: /pgtmpfs12

  mysql57:
    image: mysql:5.7
    command: mysqld
    restart: unless-stopped
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - '3306:3306'
    networks:
      - databases
    tmpfs: /var/lib/mysql5.7

  mysql8:
    image: mysql:8.0.22
    command: mysqld
    restart: unless-stopped
    platform: linux/x86_64
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - '3307:3306'
    networks:
      - databases
    tmpfs: /var/lib/mysql8

  mariadb:
    image: mariadb:10
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - '3308:3306'
    networks:
      - databases
    tmpfs: /var/lib/mariadb

networks:
  databases:
